### PR TITLE
avoid unneeded line arithm

### PR DESCRIPTION
**Pull request by tcheukueppo**
Hello Mr. Trizen

Amazing project, kudos!!

I think if `length($error_line)` is `80` then every vars remains unchanged. Correct me if I'm wrong please.

### CODE REVIEW

**Comment by trizen** [comment]
Can you, please, provide a code example illustrating the bug? Thanks

**Comment by tcheukueppo** [comment]
it is not a bug but rather an improvement.

```
        if (length($error_line) >= 80) {

            if ($point > 60) {

                my $from = $point - 40;
                my $rem  = $point + 40 - length($error_line);

                $from -= $rem;
                $point = 40 + $rem;

                $error_line = substr($error_line, $from, 80);
            }
            else {
                $error_line = substr($error_line, 0, 80);
            }
        }

```
1. if length of `$error_line` is `80` and and `$point` is < `60` then `$error_line = substr($error_line, 0, 80);` gets executed for no reason? performance improvement comes in to play here

2. Assuming that `$point` is 61 and length of `$error_line` is `80` then we recompute for nothing again

see

`$point` gets back to 61 and `$from` is zero.

Maybe I'm fucking up?

**Comment by tcheukueppo** [comment]
#offtopic

Module: `Parser.pm`, method: `get_quoted_string`, line: `:265`
`if (m{\G(?<main>$beg_delim((?>[^\\$re_delim]*+(?>\\.[^\\$re_delim]*|(?&main)){0,}){0,})$end_delim)}sgc) {`

Sorry, I'm new to sidef and I haven't seen any declaration related to this in the sidef book.

I'll like to have a variable declaration for which the parser is going to recurse to the named capture `main`. Thanks.

**Comment by trizen** [comment]
Thanks! You're correct.

**Comment by trizen** [comment]
Regarding the off topic question, Sidef regular expressions are compatible with Perl regular expressions. Therefore, any regex that is valid in Perl, is valid in Sidef as well.

**Pull request merged**
